vitaminChecker function works, but gives some errors in the terminal,
ERROR in src/app/select-food-page/select-food-page.component.ts(54,48): error TS2339: Property 'Description' does not exist on type 'Food'.
src/app/select-food-page/select-food-page.component.ts(62,44): error TS2339: Property 'Data' does not exist on type 'Food'.

The function still works though.